## 3.1

### a.

Entropy(initial) = -( 1/2 \* log2(1/2) + 1/2 \* log2(1/2) )<br>
                 = -( 1/2 \* -1 + 1/2 \* -1 )<br>
                 = -( -1/2 - 1/2 )<br>
                 = -( -1 )<br>
                 = 1<br>

Price:WillWait 

\$$$:Yes - 1/12

\$$$:No  - 2/12

\$$:Yes  - 2/12

\$$:No   - 0/12

\$:Yes   - 3/12

\$:No    - 4/12

Remainder(Price)  = 7/12 \* Entropy(\$) + 2/12 \* Entropy(\$\$) + 3/12 \* Entropy(\$\$\$)<br><br>
                  = 7/12 \* - (4/7 \* log2(4/7) + 3/7 \* log2(3/7))<br>
                  + 2/12 \* 0<br>
                  + 3/12 \* - (1/3 \* log2(1/3) + 2/3 \* log2(2/3))<br><br>
                  = 7/12 \* - (4/7 \* -0.80735492205 + 3/7 \* -1.22239242134)<br>
                  + 0<br>
                  + 3/12 \* - (1/3 \* -1.58496250072 + 2/3 \* -0.58496250072)<br><br>
                  = 7/12 \* - (-0.98522813603) + 0 + 3/12 \* - (-0.91829583405)<br><br>
                  = 0.57471641268 + 0 + 0.22957395851<br><br>
                  = 0.8042903712<br><br>

Gain(Hungry) = Entropy(initial) - Remainder(Price) <br>
             = 1 - 0.8042903712<br>
             = 0.1957096288<br>

This question would likely be worse than the Patrons? question, but
better than the Type? question. Gain(Patrons) was significantly higher
than Gain(Hungry), at 0.54, but Gain(Type) was lower, at 0. However,
there might be a question below Price? that perfectly divides the
remaining Yes/No WillWait responses, resulting in it being better than
Patrons?, but purely on the basis of information gain it is inferior to
Patrons?.

## 3.2

Our network that we built in class essentially had 3 layers: a layer with 2 input nodes, a layer below that with an AND-weighted and an OR-weighted node, and a final layer below that with a single NAND-weighted node. The layers were densely connected and strictly sequential; both input nodes on layer 1 and the bias fed into both nodes on layer 2, and both nodes on layer 2, along with a bias, fed into the final AND node on layer 3. The overall result was that the final output was a 1 only if the AND node on layer 2 was false, but the OR node on layer 2 was true. And this would obviously only occur if either input node was true, but not both, or an XOR.

However, this neural network structure could be simplified if we no longer require the network to be densely connected or strictly sequential. A network with 2 input nodes, a middle layer of a single node, and a final output layer of a single output node could create an identical result. Both input nodes would feed into the middle layer node, but they would also skip the middle layer to feed into the final layer as well. The middle node would feed into the final layer node for a total of 3 inputs into the final node. The middle layer node would be a simple AND node, outputting a 1 only if the two input nodes were 1s. The final layer would be sort of a 3-input OR node; it would output a 1 if either of the first layer input nodes was 1, unless the middle layer also output a 1. Essentially, it would act as both an OR for the first layer nodes, and a NAND for the first layer nodes. In short, the final output is a 1 only if either input node was true, but not both, or an XOR.

Poorly drawn example schematic:

[input]-- $\;\;\;\;\;\;$ --[input]
<br>
$\;\;\;\;$|$\;\;\;\;\;\;$|$\;\;\;\;\;$|$\;\;\;\;\;\;\;$|
<br>
$\;\;\;\;$|$\;\;\;\;$ 1 $\;\;$ 1 $\;\;\;\;\;$|
<br> 
$\;\;\;\;$|$\;\;\;\;\;\;$|$\;\;\;\;\;$|$\;\;\;\;\;\;\;$|
<br> 
$\;\;\;\;$|$\;\;\;\;\;\;$[1.1]$\;\;\;\;\;\;\;$|
<br>
$\;\;\;\;$|$\;\;\;\;\;\;\;\;$|$\;\;\;\;\;\;\;\;\;$|
<br>
$\;\;$ 1 $\;\;\;\;$ -2 $\;\;\;\;\;$ 1
<br>
$\;\;\;\;$|$\;\;\;\;\;\;\;\;$|$\;\;\;\;\;\;\;\;\;$|
<br>
$\;\;\;\;$------[0.1]------
    
Legend: --#-- is the input weight.
        [#] is the threshold for outputting 1 instead of 0.
        
Example: 

0 for both inputs. Middle layer node has an input of 0 \* 1 + 0 \* 1 = 0. 0 < 1.1, so it has an output of 0. Final layer node has an input of 0 \* 1 + 0 \* -2 + 0 \* 1 = 0. 0 < 0.1 so it outputs a 0.

1 for one input, 0 for the other. Middle layer node has an input of 1 \* 1 + 0 \* 1 = 1. 1 < 1.1, so it has an output of 0. Final layer node has an input of 1 \* 1 + 0 \* -2 + 0 \* 1 = 1. 1 > 0.1 so it outputs a 1.

1 for both inputs. Middle layer node has an input of 1 \* 1 + 1 \* 1 = 2. 2 > 1.1, so it has an output of 1. Final layer node has an input of 1 \* 1 + 1 \* -2 + 1 \* 1 = 0. 0 < 0.1 so it outputs a 0.

Overall:

Input1 | Input2 | Output<br>
0 $\;\;\;\;\;\;$ | 0 $\;\;\;\;\;$ | 0<br>
1 $\;\;\;\;\;\;$ | 0 $\;\;\;\;\;$ | 1<br>
0 $\;\;\;\;\;\;$ | 1 $\;\;\;\;\;$ | 1<br>
1 $\;\;\;\;\;\;$ | 1 $\;\;\;\;\;$ | 0<br>

## 3.3

In [32]:
import numpy as np
import pandas as pd
boston_df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")
boston_df = boston_df.reindex(np.random.permutation(boston_df.index))
boston_df.head()

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
405  67.92080   0.0  18.10     0  0.693  5.683  100.0  1.4254   24  666   
60    0.14932  25.0   5.13     0  0.453  5.741   66.2  7.2254    8  284   
455   4.75237   0.0  18.10     0  0.713  6.525   86.5  2.4358   24  666   
9     0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   
121   0.07165   0.0  25.65     0  0.581  6.004   84.1  2.1974    2  188   

     ptratio       b  lstat  medv  
405     20.2  384.97  22.98   5.0  
60      19.7  395.11  13.15  18.7  
455     20.2   50.92  18.13  14.1  
9       15.2  386.71  17.10  18.9  
121     19.1  377.67  14.27  20.3

### a.

In [33]:
boston_df.shape

(506, 14)

We have 506 samples. Each sample has 14 features.

### b.

In [34]:
train_data = boston_df.head(404)
val_data = train_data.tail(101)
train_data = train_data.head(303)
test_data = boston_df.tail(104)

In [35]:
train_data.shape

(303, 14)

In [36]:
val_data.shape

(101, 14)

In [37]:
test_data.shape

(104, 14)

train_data is our training set.
val_data is our validation set.
test_data is our testing set.

Our training set has 303 samples. Our validation set has 101 samples. Our test set has 104 samples.

### c.

In [38]:
boston_df['proportion_black'] = boston_df[['b']].apply(lambda x: ((x ** 0.5)/ 1000) + 0.63)

'proportion_black' is the proportion of black people by town. Since 'b' represents 1000 * (proportion_black-0.63) ^ 2, adding a synthetic variable that backtransforms this equation may be useful, giving us less altered, raw data. This could create opportunities for a model to predict things like the student/teacher ratio based on the proportion of black people by town, potentially indicating if there is systemic racism in this regard.

In [39]:
boston_df.shape

(506, 15)